### ISSUE TITLE
常馨戈-访问不到图片，报404

### ISSUE THREAD

**Issue by kuma0906** [guoyang123/shopping#128]
已经更改了img权限
但访问生成的图片地址时一直是404
在控制台里只显示一句“开始连接FTP服务器”就没有了，没有任何报错

**Comment by guoyang123** [comment]
图片上传到服务器了吗？

**Comment by guoyang123** [comment]
图片上传到服务器了吗？

**Comment by kuma0906** [comment]
上传不到

**Comment by kuma0906** [comment]
https://wenku.baidu.com/view/88f1d4429a6648d7c1c708a1284ac850ad020416.html
根据文档将ftp卸载，再重装
