### ISSUE TITLE
邢丽媛-注解错误

### ISSUE THREAD

**Issue by dsgxly** [guoyang123/shopping#4]
<img width="286" alt="1" src="https://user-images.githubusercontent.com/43959194/47638849-bc930b80-db9a-11e8-8b5a-ecdf30cfe214.png">
<img width="437" alt="default" src="https://user-images.githubusercontent.com/43959194/47638857-c3ba1980-db9a-11e8-8802-599d2954bbae.png">

将注解改成@RestControllor

**Comment by JQueenB** [comment]
也可以在方法前加上@ResponseBody
