### ISSUE TITLE
宋嘉矗-阿里云tomcat访问不到。

### ISSUE THREAD

**Issue by kingdomjc** [guoyang123/shopping#40]

**Comment by kingdomjc** [comment]
如果tomcat有问题可以把tomcat下的conf目录下的server.xml文件中的内容换成这个
<?xml version="1.0" encoding="UTF-8"?>
<Server port="8006" shutdown="SHUTDOWN">
<Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
<Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
<Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
<Listener className="org.apache.catalina.core.AprLifecycleListener"/>
<GlobalNamingResources>
<Resource name="UserDatabase" auth="Container"
 type="org.apache.catalina.UserDatabase"
 description="User database that can be updated and saved"
 factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
 pathname="conf/tomcat-users.xml"/>
</GlobalNamingResources>
<Service name="Catalina">
<Connector port="8080"
 protocol="HTTP/1.1"
 connectionTimeout="20000"
 redirectPort="8443"
 maxThreads="1000"
 minSpareThreads="20"
 acceptCount="1000"
 maxHttpHeaderSize="65536"
 debug="0"
 disableUploadTimeout="true"
 useBodyEncodingForURI="true"
 enableLookups="false"
 URIEncoding="UTF-8"/>
<Engine name="Catalina" defaultHost="localhost">
<Realm className="org.apache.catalina.realm.LockOutRealm">
<Realm className="org.apache.catalina.realm.UserDatabaseRealm"
  resourceName="UserDatabase"/>
</Realm>
<Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
prefix="localhost_access_log." suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b" />
</Host>
</Engine>
</Service>
</Server>

kingdomjc:

**Comment by guoyang123** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Server port="8006" shutdown="SHUTDOWN">
<Listener className="e="org.apache.catalina.core.JreMemoryLeakLeakPreventionListener"/>
<Listener className="e="org.apache.catalina.mbeans.GlobalResourcourcesLifecycleListener"/>
<Listener className="e="org.apache.catalina.core.ThreadLocalLealLeakPreventionListener"/>
<Listener className="e="org.apache.catalina.core.AprLifecycleLcleListener"/>
<GlobalNamingResources>
<Resource name="UserDatabase" auth="Container"
 type="e="org.apache.catalina.UserDatabase"ase"
 description="User database that can be updated and saved"
 factory="y="org.apache.catalina.users.MemoryUserDatrDatabaseFactory"
 pathname="conf/nf/tomcat-users.xml"/>
"/>
</GlobalNamingResources>
<Service name="Catalina">
<Connector port="8080"
 protocol="HTTP/1.1"
 connectionTimeout="20000"
 redirectPort="8443"
 maxThreads="1000"
 minSpareThreads="20"
 acceptCount="1000"
 maxHttpHeaderSize="65536"
 debug="0"
 disableUploadTimeout="true"
 useBodyEncodingForURI="true"
 enableLookups="false"
 URIEncoding="UTF-8"/>
<Engine name="Catalina" defaultHost="t="localhost">
<">
<Realm className="e="org.apache.catalina.realm.LockOutRealm"alm">
<Realm className="e="org.apache.catalina.realm.UserDatabaseRaseRealm"
  resourceName="UserDatabase"/>
</Realm>
<Host name="e="localhost" ap" appBase="webapps" unpackWARs="true" autoDeploy="true">
<Valve className="e="org.apache.catalina.valves.AccessLogValvValve" directory="logs"
prefix="x="localhost_acc_access_log." suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b" />
</Host>
</Engine>
</Service>
</Server>
