### ISSUE TITLE
宋嘉矗～windows的mysql数据库在mysql中添加中文数据不乱码，但是通过项目传过去的中文的数据显示中文乱码

### ISSUE THREAD

**Issue by kingdomjc** [guoyang123/shopping#75]

**Comment by guoyang123** [comment]
在代码中设置编码格式，设置springmvc的字符编码过滤器。

**Comment by guoyang123** [comment]
字符编码拦截器
web.xml

 <filter-name>setcharacter</filter-name>
    <filter-class>
       org.springframework.web.filter.CharacterEncodingFilter
    </filter-class>
    <init-param>
        <param-name>encoding</param-name>
        <param-value>UTF-8</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>setcharacter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
