### ISSUE TITLE
白京坤-tomcat无法启动

### ISSUE THREAD

**Issue by JQueenB** [guoyang123/shopping#93]
![3](https://user-images.githubusercontent.com/44011136/47949962-3144bc00-df86-11e8-8825-84b876ae072b.jpg)
如上图勾选以后tomcat无法启动并报如下错误：
![2018-11-03_161415](https://user-images.githubusercontent.com/44011136/47949969-4f122100-df86-11e8-9c59-4b8a2b6384d7.jpg)
![2](https://user-images.githubusercontent.com/44011136/47949972-53d6d500-df86-11e8-88b9-209880dfe16c.jpg)
批注：去掉勾选之后可以正常启动

**Comment by JQueenB** [comment]
![2018-11-03_195930](https://user-images.githubusercontent.com/44011136/47951943-0583ff00-dfa3-11e8-9e5f-9dfc5824579c.jpg)
有配置过

**Comment by guoyang123** [comment]
> ![2018-11-03_195930](https://user-images.githubusercontent.com/44011136/47951943-0583ff00-dfa3-11e8-9e5f-9dfc5824579c.jpg)
> 有配置过

docBase配置E盘的具体存在的目录 比如E:/test

**Comment by JQueenB** [comment]
![1](https://user-images.githubusercontent.com/44011136/47952085-2b120800-dfa5-11e8-86e4-35c05f9b6efd.jpg)
改过 了，还是一样的报错

**Comment by guoyang123** [comment]
> ![1](https://user-images.githubusercontent.com/44011136/47952085-2b120800-dfa5-11e8-86e4-35c05f9b6efd.jpg)
> 改过 了，还是一样的报错

把错误信息都贴上来

**Comment by JQueenB** [comment]
server.xml文件有问题。

**Comment by JQueenB** [comment]
![g](https://user-images.githubusercontent.com/44011136/47952489-0f116500-dfab-11e8-93c9-0ab36eb1203d.jpg)
为了和eclipse版本匹配，server.xml里多配置了一段虚拟路径。如上图所示。
删掉就可以用了，但是eclipse的问题就得另行解决了。
