### ISSUE TITLE
陈姣杨-@Autowired不能用

### ISSUE THREAD

**Issue by dreamersss** [guoyang123/shopping#94]
![error_5](https://user-images.githubusercontent.com/28667553/47950009-2e969680-df87-11e8-9ab9-a2f9b4564c8c.PNG)

**Comment by kuma0906** [comment]
好的

**Comment by dreamersss** [comment]
![error_6](https://user-images.githubusercontent.com/28667553/47961564-7c270800-e048-11e8-8282-20a2533e3223.png)

**Comment by dreamersss** [comment]
![error_6](https://user-images.githubusercontent.com/28667553/47962056-a630f800-e051-11e8-8190-cc0ecb2936c6.png)
